// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare build.
import { default as handler } from "./.open-next/worker.js";
import { processIncompleteEmailBroadcastBatches } from "./lib/server/admin";

export default {
  fetch: handler.fetch,

  async scheduled(controller: { cron: string }, env: Record<string, unknown>, ctx: { waitUntil: (promise: Promise<unknown>) => void }) {
    const limit = Number(env.ADMIN_BROADCAST_CRON_LIMIT || 3);
    const run = processIncompleteEmailBroadcastBatches(Number.isFinite(limit) ? limit : 3).then((results) => {
      console.log(
        "Processed email broadcast batches from scheduled trigger.",
        JSON.stringify({
          cron: controller.cron,
          processed: results.length,
          remaining: results.reduce((total, result) => total + result.remaining, 0)
        })
      );
    });
    ctx.waitUntil(run);
  }
};
